dist: trusty
language: java
matrix:
    include:
        -   os: linux
            jdk: oraclejdk8
       #-   os: osx
       #     osx_image: xcode10.3
script: mvn verify -DskipITs -DskipSign -B
install: true
notifications:
   email:
    recipients:
      - iftiali@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
   # Extra packages
addons:
    apt:
        packages:
            - gnupg
            - fakeroot
            - oracle-java8-unlimited-jce-policy
